services:
  goauth:
    build:
      context: .
      target: go-dev
    container_name: goauth
    ports:
      - 8001:8000
    volumes:
      - .:/app
    env_file: ".env"
    networks:
      - appnet

  postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db-data:

networks:
  appnet:
